<div class="folder">
    <span class="folderSize">{{size}}</span>
	<span class="folderLevel">{{level}}</span>
	<span class="folderOwner">{{owner}}</span>
	<span class="folderPermissions">{{permissions}}</span>
	<span class="folderGroup">{{group}}</span>
	<span class="folderID">{{ID}}</span>
    <span class="folderName">{{name|raw}}</span>
	<div class="subfolders">
		{{subfolders|raw}}
	</div>
	<div class="files">
		{{files|raw}}
	</div>
</div>